const SET_CURRENT_CONVERSATION = 'SET_CURRENT_CONVERSATION';
const GET_CONVERSATIONS = 'GET_CONVERSATIONS';
const GET_CONVERSATIONS_RECEIVED = 'GET_CONVERSATIONS_RECEIVED';

export {
	SET_CURRENT_CONVERSATION,
	GET_CONVERSATIONS,
	GET_CONVERSATIONS_RECEIVED
};
