const POST_SIGNUP = 'POST_SIGNUP';
const POST_SIGNUP_RECEIVED = 'POST_SIGNUP_RECEIVED';
const POST_SIGNIN = 'POST_SIGNIN';
const POST_SIGNIN_RECEIVED = 'POST_SIGNIN_RECEIVED';
const GET_VERIFY_NICKNAME = 'GET_VERIFY_NICKNAME';
const GET_VERIFY_NICKNAME_RECEIVED = 'GET_VERIFY_NICKNAME_RECEIVED';
const RESET_VERIFY_NICKNAME = 'RESET_VERIFY_NICKNAME';
const RESET_SIGNIN = 'RESET_SIGNIN';

export {
	POST_SIGNIN,
	POST_SIGNIN_RECEIVED,
	RESET_SIGNIN,
	POST_SIGNUP,
	POST_SIGNUP_RECEIVED,
	GET_VERIFY_NICKNAME,
	GET_VERIFY_NICKNAME_RECEIVED,
	RESET_VERIFY_NICKNAME,
};
