const POST_SIGNUP = 'POST_SIGNUP';
const POST_SIGNUP_RECEIVED = 'POST_SIGNUP_RECEIVED';
const GET_VERIFY_NICKNAME = 'GET_VERIFY_NICKNAME';
const GET_VERIFY_NICKNAME_RECEIVED = 'GET_VERIFY_NICKNAME_RECEIVED';
const RESET_VERIFY_NICKNAME = 'RESET_VERIFY_NICKNAME';

export {
	POST_SIGNUP,
	POST_SIGNUP_RECEIVED,
	GET_VERIFY_NICKNAME,
	GET_VERIFY_NICKNAME_RECEIVED,
	RESET_VERIFY_NICKNAME
};
