const POST_MESSAGE = 'POST_MESSAGE';
const POST_MESSAGE_RECEIVED = 'POST_MESSAGE_RECEIVED';
const GET_MESSAGES = 'GET_MESSAGES';
const GET_MESSAGES_RECEIVED = 'GET_MESSAGES_RECEIVED';
const RESET_MESSAGE = 'RESET_MESSAGE';

export {
	POST_MESSAGE,
	POST_MESSAGE_RECEIVED,
	GET_MESSAGES,
	GET_MESSAGES_RECEIVED,
	RESET_MESSAGE
};
