const POST_ADD_CONTACT = 'POST_ADD_CONTACT';
const POST_ADD_CONTACT_RECEIVED = 'POST_ADD_CONTACT_RECEIVED';
const RESET_ADD_CONTACT = 'RESET_ADD_CONTACT';

export {
	POST_ADD_CONTACT,
	POST_ADD_CONTACT_RECEIVED,
	RESET_ADD_CONTACT
};
