const POST_ADD_CONTACT = 'POST_ADD_CONTACT';
const POST_ADD_CONTACT_RECEIVED = 'POST_ADD_CONTACT_RECEIVED';
const GET_CONTACTS = 'GET_CONTACTS';
const GET_CONTACTS_RECEIVED = 'GET_CONTACTS_RECEIVED';
const RESET_ADD_CONTACT = 'RESET_ADD_CONTACT';
const RESET_GET_CONTACTS = 'RESET_GET_CONTACTS';
const RESET_CONTACT = 'RESET_CONTACT';

export {
	POST_ADD_CONTACT,
	POST_ADD_CONTACT_RECEIVED,
	RESET_ADD_CONTACT,
	GET_CONTACTS,
	GET_CONTACTS_RECEIVED,
	RESET_GET_CONTACTS,
	RESET_CONTACT
};
